# Disable AppVeyor's default Visual Studio build system.
build: false

# Set Rust versions.
# NOTE: If we also add in the MSVC toolchains, we'll want to set the version of
# Visual Studio that AppVeyor is using.
environment:
  matrix:
    - channel: stable
      target: x86_64-pc-windows-gnu
    - channel: stable
      target: i686-pc-windows-gnu
    - channel: beta
      target: x86_64-pc-windows-gnu
    - channel: beta
      target: i686-pc-windows-gnu
    - channel: nightly
      target: x86_64-pc-windows-gnu
    - channel: nightly
      target: i686-pc-windows-gnu

# Allow failure on nightly. We want to track behavior in these cases, but
# stability is somewhat out of our hands. In the case of beta, we want to see
# these failures coming before they reach stable, so it's best to disallow them.
matrix:
  allow_failures:
    - channel: nightly

# Install Rust using rustup.
install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -y --default-toolchain=%channel% --default-host=%target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin

# Run tests.
test_script:
  - cargo build --verbose
  - cargo test --verbose

# Send notifications.
notifications:
  - provider: Email
    to:
      - jacob@havoc.io
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
